$(document).ready(function(){
    	$("#menu").click(function(){
       	 	$("#main-content").hide();
       	 	$("#header").hide();
        	$("#dialog-1").show();
    });
    	$("#menu1").click(function(){
       	 	$("#main-content").show();
       	 	$("#header").show();
        	$("#dialog-1").hide();
    });
});